# Generated by Django 4.2 on 2023-04-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(default='...'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='text'),
        ),
    ]
